services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "8800:8800"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8800/ || exit 1" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
