services:
  backend:
    image: 910051580567.dkr.ecr.us-east-1.amazonaws.com/backend-nightly:latest
    container_name: backend_service
    restart: always
    ports:
      - "8800:8800"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8800/ || exit 1" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  frontend:
    image: 910051580567.dkr.ecr.us-east-1.amazonaws.com/frontend-nightly:latest
    container_name: frontend_service
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
