services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "8800:8800"
    environment:
      DB_HOST: "mysql-db.cdegrojvvejq.us-east-1.rds.amazonaws.com"
      DB_USER: "root"
      DB_PASSWORD: "164450zsq"
      DB_NAME: "test"
      DB_PORT: "3306"
    volumes:
      - ./backend:/user/src/app
      - /user/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"