services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "8800:8800"
    environment:
      DB_HOST: "mysql-db.cdegrojvvejq.us-east-1.rds.amazonaws.com"
      DB_USER: "root"
      DB_PASSWORD: "164450zsq"
      DB_NAME: "test"
      DB_PORT: "3306"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8800/"]
      interval: 10s
      retries: 5
      timeout: 5s

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
