name: Nightly Build and Deployment

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and tag backend Docker image
        run: |
          docker build -t backend-nightly:latest ./backend

      - name: Build and tag frontend Docker image
        run: |
          docker build -t frontend-nightly:latest ./frontend

      - name: Run tests
        run: |
          docker-compose up -d
          sleep 10 # Wait for services to start
          docker exec backend_service npm test || exit 1 # Run backend tests
          docker exec frontend_service npm test || exit 1 # Run frontend tests

  notify-failure:
    if: failure()
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email notification
        run: |
          curl --url "smtp://smtp.ethereal.email:587" --ssl-reqd \
          --mail-from "bryana.fay71@ethereal.email" \
          --mail-rcpt "qa-team@example.com" \
          --user "bryana.fay71@ethereal.email:6XF4g3kB5xSBngJxBt" \
          --upload-file - <<EOF
          From: BryanaFay <bryana.fay71@ethereal.email>
          To: QA Team <qa-team@example.com>
          Subject: Nightly Build Failed!
          
          The nightly build has failed. Please check the GitHub Actions logs for details.
          EOF
